name: Build and deploy ASP app to Azure Web App - kamranwebapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore learningapp/learningapp.csproj

      - name: Build
        run: dotnet build learningapp/learningapp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish learningapp/learningapp.csproj --configuration Release --output ./published --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_046A0CD61FC0456D9F441B2DFCB06874 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B9652A99F864647AD7E2190FB3602E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_617953952DBF40A282F6ABD586DE0CCA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kamranwebapp1'
          slot-name: 'Production'
          package: ASP-app
